version: '3.8'

x-parser-template: &parser-template
  build: ./parser
  depends_on:
    - backend
  restart: always

x-middleware-parser-template: &middleware-parser-template
  build: ./middleware-parser
  depends_on:
    - backend
  restart: always

services:
  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    restart: always

  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - pgdb
    restart: always

  frontend:
    build: ./frontend
    ports:
      - '80:3000'
    restart: always

  cards-parser:
    build: ./cards-parser
    depends_on:
      - backend
    restart: always

  parser1:
    <<: *parser-template
    environment:
      - CNT=1

  parser2:
    <<: *parser-template
    environment:
      - CNT=2

  parser3:
    <<: *parser-template
    environment:
      - CNT=3

  parser4:
    <<: *parser-template
    environment:
      - CNT=4

  parser5:
    <<: *parser-template
    environment:
      - CNT=5

  parser6:
    <<: *parser-template
    environment:
      - CNT=6

  parser7:
    <<: *parser-template
    environment:
      - CNT=7

  parser8:
    <<: *parser-template
    environment:
      - CNT=8

  parser9:
    <<: *parser-template
    environment:
      - CNT=9

  parser10:
    <<: *parser-template
    environment:
      - CNT=10

  middleware-parser1:
    <<: *middleware-parser-template
    environment:
      - CNT=1

  middleware-parser2:
    <<: *middleware-parser-template
    environment:
      - CNT=2

  middleware-parser3:
    <<: *middleware-parser-template
    environment:
      - CNT=3

  middleware-parser4:
    <<: *middleware-parser-template
    environment:
      - CNT=4

  middleware-parser5:
    <<: *middleware-parser-template
    environment:
      - CNT=5

  middleware-parser6:
    <<: *middleware-parser-template
    environment:
      - CNT=6

  middleware-parser7:
    <<: *middleware-parser-template
    environment:
      - CNT=7

  middleware-parser8:
    <<: *middleware-parser-template
    environment:
      - CNT=8

  middleware-parser9:
    <<: *middleware-parser-template
    environment:
      - CNT=9

  middleware-parser10:
    <<: *middleware-parser-template
    environment:
      - CNT=10

volumes:
  pgdbdata:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
