version: '3.8'

x-parser-template: &parser-template
  build: ./parser
  depends_on:
    - backend
  restart: always

x-middleware-parser-template: &middleware-parser-template
  build: ./middleware-parser
  depends_on:
    - backend
  restart: always

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    restart: always

  pgbouncer:
    image: edoburu/pgbouncer:1.18.0
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_NAME=postgres
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=20
      - MIN_POOL_SIZE=10
      - RESERVE_POOL_SIZE=5
      - RESERVE_POOL_TIMEOUT=3
      - MAX_DB_CONNECTIONS=50
      - MAX_USER_CONNECTIONS=50
      - LOG_CONNECTIONS=1
      - LOG_DISCONNECTIONS=1
      - LOG_POOLER_ERRORS=1
      - VERBOSE=1
      - LOG_FILE=/var/log/pgbouncer/pgbouncer.log
      - PID_FILE=/tmp/pgbouncer.pid
      - SERVER_RESET_QUERY=DISCARD ALL
      - SERVER_CHECK_DELAY=30
      - SERVER_CHECK_QUERY=select 1
      - SERVER_LIFETIME=3600
      - SERVER_IDLE_TIMEOUT=600
      - CLIENT_IDLE_TIMEOUT=60
      - IDLE_TRANSACTION_TIMEOUT=600
      - QUERY_TIMEOUT=60
      - IGNORE_STARTUP_PARAMETERS=extra_float_digits
    ports:
      - "6432:6432"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - pgbouncer_logs:/var/log/pgbouncer
    tmpfs:
      - /tmp:mode=1777,size=10M
    user: "999:999"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "6432", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always

  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    restart: always

  cards-parser:
    build: ./cards-parser
    depends_on:
      - backend
    restart: always

  parser1:
    <<: *parser-template
    environment:
      - CNT=1

  parser2:
    <<: *parser-template
    environment:
      - CNT=2

  parser3:
    <<: *parser-template
    environment:
      - CNT=3

  parser4:
    <<: *parser-template
    environment:
      - CNT=4

  parser5:
    <<: *parser-template
    environment:
      - CNT=5

  parser6:
    <<: *parser-template
    environment:
      - CNT=6

  parser7:
    <<: *parser-template
    environment:
      - CNT=7

  parser8:
    <<: *parser-template
    environment:
      - CNT=8

  parser9:
    <<: *parser-template
    environment:
      - CNT=9

  parser10:
    <<: *parser-template
    environment:
      - CNT=10

  middleware-parser1:
    <<: *middleware-parser-template
    environment:
      - CNT=1

  middleware-parser2:
    <<: *middleware-parser-template
    environment:
      - CNT=2

  middleware-parser3:
    <<: *middleware-parser-template
    environment:
      - CNT=3

  middleware-parser4:
    <<: *middleware-parser-template
    environment:
      - CNT=4

  middleware-parser5:
    <<: *middleware-parser-template
    environment:
      - CNT=5

  middleware-parser6:
    <<: *middleware-parser-template
    environment:
      - CNT=6

  middleware-parser7:
    <<: *middleware-parser-template
    environment:
      - CNT=7

  middleware-parser8:
    <<: *middleware-parser-template
    environment:
      - CNT=8

  middleware-parser9:
    <<: *middleware-parser-template
    environment:
      - CNT=9

  middleware-parser10:
    <<: *middleware-parser-template
    environment:
      - CNT=10

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/postgres_data
  pgbouncer_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/logs/pgbouncer