version: '3.8'

x-parser-template: &parser-template
  build: ./parser
  depends_on:
    - backend
  restart: always
  develop:
    watch:
      - path: parser/scheduler.py
        action: rebuild
      - path: parser/main.py
        action: rebuild

services:
  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    restart: always

  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - pgdb
    restart: always

  frontend:
    build: ./frontend
    ports:
      - '80:3000'
    restart: always

  parser1:
    <<: *parser-template
    environment:
      - CNT=1

  parser2:
    <<: *parser-template
    environment:
      - CNT=2

  parser3:
    <<: *parser-template
    environment:
      - CNT=3

  parser4:
    <<: *parser-template
    environment:
      - CNT=4

  parser5:
    <<: *parser-template
    environment:
      - CNT=5

  parser6:
    <<: *parser-template
    environment:
      - CNT=6

  parser7:
    <<: *parser-template
    environment:
      - CNT=7

  parser8:
    <<: *parser-template
    environment:
      - CNT=8

  parser9:
    <<: *parser-template
    environment:
      - CNT=9

  parser10:
    <<: *parser-template
    environment:
      - CNT=10

volumes:
  pgdbdata:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450