version: '3.8'

x-parser-template: &parser-template
  build: ./parser
  depends_on:
    - backend
  restart: always

services:
  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    restart: always

  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - pgdb
    restart: always

  frontend:
    build: ./frontend
    ports:
      - '80:3000'
    restart: always

  cards-parser:
    build: ./cards-parser
    depends_on:
      - backend
    restart: always

  middleware-parser:
    build: ./middleware-parser
    depends_on:
      - backend
    restart: always

  parser1:
    <<: *parser-template
    environment:
      - CNT=1

volumes:
  pgdbdata:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450