version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
volumes:
  pgdbdata: null