version: '3'
services:
  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb
    #volumes:
    #  - pgdbdata:/var/lib/postgresql/data/
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      - pgdb
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    restart: always
  parser:
    build: ./parser
    container_name: parser
    depends_on:
      - backend
volumes:
  pgdbdata: null
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
